<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>top.dlzio</groupId>
        <artifactId>dlz-kit-plugins</artifactId>
        <version>6.7.4</version>
    </parent>

    <artifactId>dlz-json-jackson</artifactId>
    <name>dlz-json-jackson</name>
    <description>Optional Jackson interoperability for DLZ JSON APIs</description>
    <properties>
        <jacoco.skip>false</jacoco.skip>
        <spotbugs.skip>false</spotbugs.skip>
        <jackson.version>2.17.3</jackson.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>top.dlzio</groupId>
            <artifactId>dlz-kit</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
